In [5]:
!python3 training.py     #step1

Using TensorFlow backend.
Classes: ['Unsafe', 'Safe']
No of Images per classes in training
13790 14437
No of Images per classes in validation
3461 2854
Found 28227 images belonging to 2 classes.
Found 6315 images belonging to 2 classes.
Train Size : 28227
Val Size : 6315
2019-01-08 19:03:48.335250: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-08 19:03:48.449105: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-08 19:03:48.449796: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.52GiB
2019-01-08 19:03:48.449809: I tensorflow/core/common_runtime/gpu/gpu_device.cc

In [7]:
!python3 training.py       #step2

Using TensorFlow backend.
Classes: ['Unsafe', 'Safe']
No of Images per classes in training
13790 14437
No of Images per classes in validation
3461 2854
Found 28227 images belonging to 2 classes.
Found 6315 images belonging to 2 classes.
Train Size : 28227
Val Size : 6315
2019-01-08 19:41:21.092766: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-08 19:41:21.205861: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-08 19:41:21.206524: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.51GiB
2019-01-08 19:41:21.206551: I tensorflow/core/common_runtime/gpu/gpu_device.cc

In [1]:
!python3 training.py        #step3

Using TensorFlow backend.
Classes: ['Unsafe', 'Safe']
No of Images per classes in training
13790 14437
No of Images per classes in validation
3461 2854
Found 28227 images belonging to 2 classes.
Found 6315 images belonging to 2 classes.
Train Size : 28227
Val Size : 6315
2019-01-09 10:41:02.648074: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-09 10:41:02.756815: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-09 10:41:02.757484: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.35GiB
2019-01-09 10:41:02.757512: I tensorflow/core/common_runtime/gpu/gpu_device.cc

In [1]:
! python3 training.py       #step-4

Using TensorFlow backend.
Classes: ['Unsafe', 'Safe']
No of Images per classes in training
13790 14437
No of Images per classes in validation
3461 2854
Found 28227 images belonging to 2 classes.
Found 6315 images belonging to 2 classes.
Train Size : 28227
Val Size : 6315
2019-01-09 15:52:12.858425: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-09 15:52:12.971560: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-09 15:52:12.972207: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.25GiB
2019-01-09 15:52:12.972220: I tensorflow/core/common_runtime/gpu/gpu_device.cc

In [3]:
!python3 training.py     #step 5 dropout

Using TensorFlow backend.
Classes: ['Unsafe', 'Safe']
No of Images per classes in training
13790 14437
No of Images per classes in validation
3461 2854
Found 28227 images belonging to 2 classes.
Found 6315 images belonging to 2 classes.
Train Size : 28227
Val Size : 6315
2019-01-09 17:14:20.501711: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-09 17:14:20.616608: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-09 17:14:20.617270: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.32GiB
2019-01-09 17:14:20.617298: I tensorflow/core/common_runtime/gpu/gpu_device.cc

In [3]:
!python3 test_images.py

Using TensorFlow backend.
2019-01-10 12:25:03.965773: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-10 12:25:04.077376: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-10 12:25:04.078003: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.23GiB
2019-01-10 12:25:04.078032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-10 12:25:04.274085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-10 12:25:04.274116: I tensorflow/core/common_runtime/

In [2]:
!python3 test_images.py

Using TensorFlow backend.
2019-01-10 11:48:13.921398: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-01-10 11:48:14.019951: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-10 11:48:14.020655: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
totalMemory: 10.91GiB freeMemory: 10.31GiB
2019-01-10 11:48:14.020671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-10 11:48:14.218991: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-10 11:48:14.219024: I tensorflow/core/common_runtime/

In [5]:
len(os.listdir('training_data_adult/Unsafe/train')),len(os.listdir('training_data_adult/Unsafe/valid'))

(6195, 1563)

In [ ]:
os.makedirs('training_data_adult/train')

In [12]:
x = np.random.uniform(low=0.0, high=1.0, size=(12691,))
x.shape

(12691,)

In [13]:
x[:10]

array([0.68776506, 0.97374719, 0.97012519, 0.56121792, 0.05826528,
       0.24371599, 0.55103166, 0.26908809, 0.65997939, 0.07874905])

In [11]:
y = np.random.uniform(low=0.0, high=1.0, size=(17190,))
y.shape

(17190,)

In [14]:
x_=x<0.2
y_=y<0.2
x_[:10],y_[:10]

(array([False, False, False, False,  True, False, False, False, False,
         True]),
 array([ True, False, False,  True, False, False,  True, False,  True,
        False]))

In [28]:
x_[12690]

False

In [24]:
j=0
for i in unsafe_fn:
    if i!='valid' or i!='train':
        src='training_data_adult/Unsafe/'+i
        if x_[j]==True:
            dst='training_data_adult/Unsafe/valid'
        elif x_[j]==False:
            dst='training_data_adult/Unsafe/train'
        move(src, dst)
        j+=1

IndexError: index 12691 is out of bounds for axis 0 with size 12691